<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.649">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lefty Lemurs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="LeftyLemurs_files/libs/clipboard/clipboard.min.js"></script>
<script src="LeftyLemurs_files/libs/quarto-html/quarto.js"></script>
<script src="LeftyLemurs_files/libs/quarto-html/popper.min.js"></script>
<script src="LeftyLemurs_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LeftyLemurs_files/libs/quarto-html/anchor.min.js"></script>
<link href="LeftyLemurs_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LeftyLemurs_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LeftyLemurs_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LeftyLemurs_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LeftyLemurs_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lefty Lemurs</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Loading library</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Here’s what I did to clean the data:</strong></p>
<p>Importing dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>L_PreClean <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Documents/GitHub/Lefty_Lemurs/LeftyLemurs_Original.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(L_PreClean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Troop.............A..B..C..D.... Focal.Lemur          Species         
 Length:694                       Length:694         Length:694        
 Class :character                 Class :character   Class :character  
 Mode  :character                 Mode  :character   Mode  :character  
                                                                       
                                                                       
                                                                       
     Sex                Month            Day             Year     
 Length:694         Min.   :6.000   Min.   : 1.00   Min.   :2022  
 Class :character   1st Qu.:6.000   1st Qu.: 8.00   1st Qu.:2022  
 Mode  :character   Median :6.000   Median :22.00   Median :2022  
                    Mean   :6.411   Mean   :18.29   Mean   :2022  
                    3rd Qu.:7.000   3rd Qu.:28.00   3rd Qu.:2022  
                    Max.   :7.000   Max.   :30.00   Max.   :2022  
 Time..H.M.S.         Category        
 Length:694         Length:694        
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      
 Focal.sample.note......................................................................................................................................................please.include.as.much.detail.as.possible...If.a.note.is.about.a.grooming.bout..for.example..include.stop.time.in.the.same.cell.
 Length:694                                                                                                                                                                                                                                                                                             
 Class :character                                                                                                                                                                                                                                                                                       
 Mode  :character                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                        </code></pre>
</div>
</div>
<p>rename long column names to simpler ones</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>L_PreClean <span class="ot">&lt;-</span> <span class="fu">rename</span>(L_PreClean, <span class="at">Troop =</span> Troop.............A..B..C..D...., <span class="at">Time =</span> Time..H.M.S., <span class="at">Note =</span> Focal.sample.note......................................................................................................................................................please.include.as.much.detail.as.possible...If.a.note.is.about.a.grooming.bout..for.example..include.stop.time.in.the.same.cell.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>remove commas in the category column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>L_PreClean<span class="sc">$</span>Category <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(L_PreClean<span class="sc">$</span>Category, <span class="st">","</span>, <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Why on earth did it make it into a value instead of a new data frame??? I guess it doesn’t matter because it still works…</p>
<p>Sometimes I wrote behaviors in all caps, and sometimes I didn’t. I’m just going to put all of them in all caps because it’s easier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>L_PreClean<span class="sc">$</span>Category <span class="ot">=</span> <span class="fu">toupper</span>(L_PreClean<span class="sc">$</span>Category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have some data where I didn’t actually record the limb used. Why did I do that? I’m going to delete the rows where I forgot to list the limb.</p>
<p>Only keep rows in categories that don’t contain RH, LH, RF, and/or LF</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>L_HFdata <span class="ot">&lt;-</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  L_PreClean <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(Category, <span class="st">"RH|RF|LH|LF"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Squeaky clean</p>
<p>Now I want to create a separate data frame that only contains behaviors from my ethogram:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># do not run </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># lefty_justEthogram &lt;-</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># L %&gt;%  select(Category) %&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># filter(str_detect(Category, "BP|QP|L|AG|SG|F|E|CL|HC|R|G|"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Why didn’t it work</p>
<p><em>This did not work</em> Would it be possible to split the “Category” column into 2 columns? 1 that says “Task” and another that says “Limb”?</p>
<p>“Limb” would have LH/RH/LF/RH and “Task” would have the other stuff</p>
<p>I think if I duplicate the column and rename it and then eliminate the limbs from “Task” and keep only the limbs in “Limbs” it might work.</p>
<p>Then I can rename the tasks to “Eating/Grooming/Locomotion/etc.</p>
<p>Duplicating “Category” and calling the new one “Limb”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># do not run: L_HFdata$Limb &lt;- L_PreClean$Category</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># do not run: L_PreClean2 &lt;- L_PreClean %&gt;% relocate (Limb, .before = Note)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>This did not work</em></p>
<p>Replacing limb with nothing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># do not run: lefty_split &lt;- L_PreClean2$Category &lt;- str_replace(L_PreClean$Limb, "BP|QP|L|AG|SG|F|E|CL|HC|R|G|", "")</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># do not run: lefty_fullsplit &lt;- L_PreClean2$Limb &lt;- str_replace(L_PreClean$Category, "LF|LH|RF|RH|", "")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Categories kept limbs because they include an R (like rest) or L (like locomotion) I think limb section stayed the same? I think it kept all the columns that contained the limbs, which was all of them ofc. I might be running the wrong code.</p>
<p>Okay I’m going to use find and replace in Excel to fix it because R doesn’t know how to do anything apparently and I literally want to cry rn</p>
<p>Wait wtf why does it say 30,000+ rows columns</p>
<section id="okay-ive-spent-4-hours-trying-to-get-it-to-work-and-tbh-this-is-a-waste-of-time-so-im-just-going-to-export-the-behavior-data-as-a-csv-and-finish-cleaning-it-in-google-sheets" class="level2">
<h2 class="anchored" data-anchor-id="okay-ive-spent-4-hours-trying-to-get-it-to-work-and-tbh-this-is-a-waste-of-time-so-im-just-going-to-export-the-behavior-data-as-a-csv-and-finish-cleaning-it-in-google-sheets">okay I’ve spent 4 hours trying to get it to work and tbh this is a waste of time so I’m just going to export the behavior data as a CSV and finish cleaning it in Google Sheets</h2>
<p>Writing as CSV bc my attempts at making limb column completely failed after working on it for 2 days</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write_csv(L_PreClean,"Lefty_Lemurs.csv")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>Here’s what I did in Google Sheets with the CSV file</strong> (I really wanted to do it in R but I could not figure it out and wasted hours and hours)</p>
<ul>
<li>Deleted rows that didn’t contain behaviors from my ethogram</li>
<li>Copied “Category” into 2 columns</li>
<li>In old Category column, deleted limb data</li>
<li>In new “Limb” data, kept only limb data (not behavior)</li>
<li>Deleted rows that had question marks in data</li>
<li>Deleted data where category was “Other”</li>
<li>Deleted data that had rows with both hands</li>
<li>Merged “F” and “E” into one category “E”</li>
<li>Looked through notes to change category when it was just “G”. Most got changed to L, some got changed to R, a few got deleted</li>
<li>Added new column for H/F to say whether limb was hand or foot</li>
<li>Added new column for side to say whether limb was left or right</li>
</ul>
<p>New categories - E (eating/foraging) - R (resting) (lemur is still) - L (locomotion) (active motion like leaping, climbing, or jumping) - CL (cross legs) - HC (hand clasp) - BP (bipedal walking) - QP (quadrupedal walking) - LA (land) - SG (self grooming) - AG (allo-grooming)</p>
<p><strong><em>Upload clean data</em></strong> (it was a nightmare of cleaning this data in R and Excel and took many terrible hours, of which I do not wish to relive)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>L <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Documents/GitHub/Lefty_Lemurs/LeftyLemurs_Clean.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Analysis</strong></p>
<p>~Hex codes for colors (to use in graphs)~ Red: #C84E00 Orange: #E89923 Yellow: #FFD960 Light Green: #A1B70D Turquoise: #339898 Teal: #1D6363 Medium Blue: #005587 Light Blue: #0577B1 Purple: #993399</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Troop    Focal Species Age Sex Month Day Year    Time Category Limb H.F Side
1     P Carolina    Emon  12   F     6  30 2022 8:25:26        E   RH   H    R
2     P Carolina    Emon  12   F     6  30 2022 8:28:29        E   RH   H    R
3     P Carolina    Emon  12   F     6  30 2022 8:23:54        E   LH   H    L
4     P Carolina    Emon  12   F     6  30 2022 8:25:47        E   LH   H    L
5     P Carolina    Emon  12   F     6  30 2022 8:27:13        E   LH   H    L
6     P Carolina    Emon  12   F     6  30 2022 8:43:36        E   LH   H    L
                                              Note
1        Grasp silverberry with right hand and eat
2 Grasp and eat silverberry with right hand on top
3          Grab silverberry with left hand and eat
4         Grasp silverberry with left hand and eat
5   Grasp silverberry plant with left hand and eat
6   Forage and eat evergreen leaves with left hand</code></pre>
</div>
</div>
<p>Let’s look at how many total instances of each limb use there was</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(L<span class="sc">$</span>Limb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 LF  LH  RF  RH 
 32 225  47 318 </code></pre>
</div>
</div>
<p>Omg</p>
<p>Left Hand: 225 Right Hand: 318 Left Foot: 32 Right Foot: 47</p>
<p>It looks like lemurs used their right hands a lot more than they used their left hands…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span> (Limb, Limb, table ))) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#012169"</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Limb"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Total Limb Use Across Lemurs"</span>) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Yep, there definitely appears to be a hand/foot preference</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span> (Limb, Limb, table ))) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Limb"</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Total Limb Use Across Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span> (Side, Side, table ))) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right"</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Same thing but on the same scale (I got more data from sifakas as u can see)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species,)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>👀 Sifakas have higher left hand use than the other 2 species. Sifakas overall seem more ambidextrous. However, this could be due to them foraging more (maybe all lemurs forage more with their left hands or something idk). Therefore I should separate it out by eating behaviors.</p>
<p>What about by sex</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span> (Limb, Limb, table ))) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#1D6363"</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Limb"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Total Limb Use Between Sexes: Lemurs Are Not Lefties"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is the same thing but just divided by left and right side (left hand and left foot, etc. are in the same category)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span> (Side, Side, table ))) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#1D6363"</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Total Limb Use Between Sexes: Lemurs Are Not Lefties"</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Definitely more right hand than left HAND use for both males and females. Not sure about foot use, but I didn’t get much foot use data to begin with. Is there a way to exclude foot use?</p>
<p>Males might me a little less lateralized than females? Left hand use is also (slightly) higher in males like I thought it would be!</p>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span> (Category, Category, table ))) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#0577B1"</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Type of Behavior"</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Total Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Behavior Across Sexes"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex,<span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Everyone eats a lot</p>
<p>Some calculations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Troop              Focal             Species               Age    
 Length:622         Length:622         Length:622         Min.   : 5  
 Class :character   Class :character   Class :character   1st Qu.:10  
 Mode  :character   Mode  :character   Mode  :character   Median :12  
                                                          Mean   :12  
                                                          3rd Qu.:14  
                                                          Max.   :29  
     Sex                Month            Day             Year     
 Length:622         Min.   :6.000   Min.   : 1.00   Min.   :2022  
 Class :character   1st Qu.:6.000   1st Qu.: 8.00   1st Qu.:2022  
 Mode  :character   Median :6.000   Median :22.00   Median :2022  
                    Mean   :6.436   Mean   :18.04   Mean   :2022  
                    3rd Qu.:7.000   3rd Qu.:28.00   3rd Qu.:2022  
                    Max.   :7.000   Max.   :30.00   Max.   :2022  
     Time             Category             Limb               H.F           
 Length:622         Length:622         Length:622         Length:622        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
     Side               Note          
 Length:622         Length:622        
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(L[<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)], <span class="at">group =</span> <span class="st">"Category"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Descriptive statistics by group 
Category: BP
          vars  n    mean    sd median trimmed   mad  min  max range  skew
Age          1 48    8.71  4.93   10.0    8.00  0.00    5   29    24  2.74
Troop*       2 48    1.17  0.48    1.0    1.05  0.00    1    3     2  2.78
Focal*       3 48    2.54  1.43    2.5    2.55  2.22    1    4     3 -0.04
Species*     4 48    1.96  0.20    2.0    2.00  0.00    1    2     1 -4.44
Age.1        5 48    8.71  4.93   10.0    8.00  0.00    5   29    24  2.74
Sex*         6 48    1.58  0.50    2.0    1.60  0.00    1    2     1 -0.33
Month        7 48    6.56  0.50    7.0    6.58  0.00    6    7     1 -0.24
Day          8 48   12.92 10.58   14.0   12.85 14.83    1   27    26  0.01
Year         9 48 2022.00  0.00 2022.0 2022.00  0.00 2022 2022     0   NaN
Time*       10 48   24.50 14.00   24.5   24.50 17.79    1   48    47  0.00
Category*   11 48    1.00  0.00    1.0    1.00  0.00    1    1     0   NaN
Limb*       12 48    1.56  0.50    2.0    1.57  0.00    1    2     1 -0.24
H.F*        13 48    1.00  0.00    1.0    1.00  0.00    1    1     0   NaN
          kurtosis   se
Age           9.10 0.71
Troop*        6.93 0.07
Focal*       -1.93 0.21
Species*     18.13 0.03
Age.1         9.10 0.71
Sex*         -1.93 0.07
Month        -1.98 0.07
Day          -1.86 1.53
Year           NaN 0.00
Time*        -1.28 2.02
Category*      NaN 0.00
Limb*        -1.98 0.07
H.F*           NaN 0.00
------------------------------------------------------------ 
Category: CL
          vars  n    mean   sd median trimmed  mad  min  max range  skew
Age          1 16   15.25 3.61   17.0   15.86 0.00    5   17    12 -1.74
Troop*       2 16    1.81 0.40    2.0    1.86 0.00    1    2     1 -1.45
Focal*       3 16    2.88 0.72    3.0    2.93 0.00    1    4     3 -0.85
Species*     4 16    1.19 0.40    1.0    1.14 0.00    1    2     1  1.45
Age.1        5 16   15.25 3.61   17.0   15.86 0.00    5   17    12 -1.74
Sex*         6 16    1.25 0.45    1.0    1.21 0.00    1    2     1  1.05
Month        7 16    6.25 0.45    6.0    6.21 0.00    6    7     1  1.05
Day          8 16   18.81 9.52   21.0   19.29 6.67    1   30    29 -0.76
Year         9 16 2022.00 0.00 2022.0 2022.00 0.00 2022 2022     0   NaN
Time*       10 16    8.50 4.76    8.5    8.50 5.93    1   16    15  0.00
Category*   11 16    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
Limb*       12 16    1.94 0.25    2.0    2.00 0.00    1    2     1 -3.28
H.F*        13 16    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
          kurtosis   se
Age           1.68 0.90
Troop*        0.13 0.10
Focal*        0.92 0.18
Species*      0.13 0.10
Age.1         1.68 0.90
Sex*         -0.95 0.11
Month        -0.95 0.11
Day          -0.85 2.38
Year           NaN 0.00
Time*        -1.43 1.19
Category*      NaN 0.00
Limb*         9.36 0.06
H.F*           NaN 0.00
------------------------------------------------------------ 
Category: E
          vars   n    mean    sd median trimmed    mad  min  max range   skew
Age          1 312   12.27  7.01   12.0   11.10   2.97    5   29    24   1.23
Troop*       2 312    3.87  1.75    4.0    3.96   1.48    1    6     5  -0.57
Focal*       3 312    7.41  3.47    8.0    7.62   4.45    1   12    11  -0.43
Species*     4 312    1.88  0.85    2.0    1.85   1.48    1    3     2   0.23
Age.1        5 312   12.27  7.01   12.0   11.10   2.97    5   29    24   1.23
Sex*         6 312    1.71  0.45    2.0    1.76   0.00    1    2     1  -0.93
Month        7 312    6.36  0.48    6.0    6.33   0.00    6    7     1   0.57
Day          8 312   19.35 10.46   24.0   20.17   8.90    1   30    29  -0.52
Year         9 312 2022.00  0.00 2022.0 2022.00   0.00 2022 2022     0    NaN
Time*       10 312  154.60 89.04  153.5  154.50 113.42    1  309   308   0.01
Category*   11 312    1.00  0.00    1.0    1.00   0.00    1    1     0    NaN
Limb*       12 312    2.60  0.50    3.0    2.63   0.00    1    3     2  -0.54
H.F*        13 312    1.99  0.08    2.0    2.00   0.00    1    2     1 -12.31
          kurtosis   se
Age           0.98 0.40
Troop*       -1.07 0.10
Focal*       -0.88 0.20
Species*     -1.57 0.05
Age.1         0.98 0.40
Sex*         -1.14 0.03
Month        -1.68 0.03
Day          -1.36 0.59
Year           NaN 0.00
Time*        -1.20 5.04
Category*      NaN 0.00
Limb*        -1.35 0.03
H.F*        150.02 0.00
------------------------------------------------------------ 
Category: HC
          vars n    mean   sd median trimmed  mad  min  max range  skew
Age          1 4   11.50 3.00   10.0   11.50 0.00   10   16     6  0.75
Troop*       2 4    1.25 0.50    1.0    1.25 0.00    1    2     1  0.75
Focal*       3 4    1.75 0.50    2.0    1.75 0.00    1    2     1 -0.75
Species*     4 4    1.75 0.50    2.0    1.75 0.00    1    2     1 -0.75
Age.1        5 4   11.50 3.00   10.0   11.50 0.00   10   16     6  0.75
Sex*         6 4    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
Month        7 4    6.75 0.50    7.0    6.75 0.00    6    7     1 -0.75
Day          8 4   10.25 8.50    6.0   10.25 0.00    6   23    17  0.75
Year         9 4 2022.00 0.00 2022.0 2022.00 0.00 2022 2022     0   NaN
Time*       10 4    2.50 1.29    2.5    2.50 1.48    1    4     3  0.00
Category*   11 4    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
Limb*       12 4    1.25 0.50    1.0    1.25 0.00    1    2     1  0.75
H.F*        13 4    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
          kurtosis   se
Age          -1.69 1.50
Troop*       -1.69 0.25
Focal*       -1.69 0.25
Species*     -1.69 0.25
Age.1        -1.69 1.50
Sex*           NaN 0.00
Month        -1.69 0.25
Day          -1.69 4.25
Year           NaN 0.00
Time*        -2.08 0.65
Category*      NaN 0.00
Limb*        -1.69 0.25
H.F*           NaN 0.00
------------------------------------------------------------ 
Category: L
          vars  n    mean    sd median trimmed   mad  min  max range  skew
Age          1 76   11.78  6.11   12.0   10.98  5.93    5   29    24  1.15
Troop*       2 76    4.12  1.42    5.0    4.24  1.48    1    6     5 -0.84
Focal*       3 76    5.14  3.36    5.0    4.97  4.45    1   12    11  0.15
Species*     4 76    1.59  0.82    1.0    1.50  0.00    1    3     2  0.86
Age.1        5 76   11.78  6.11   12.0   10.98  5.93    5   29    24  1.15
Sex*         6 76    1.53  0.50    2.0    1.53  0.00    1    2     1 -0.10
Month        7 76    6.17  0.38    6.0    6.10  0.00    6    7     1  1.71
Day          8 76   23.16  6.95   27.0   23.98  4.45    6   30    24 -0.91
Year         9 76 2022.00  0.00 2022.0 2022.00  0.00 2022 2022     0   NaN
Time*       10 76   38.49 22.06   38.5   38.50 28.17    1   75    74  0.00
Category*   11 76    1.00  0.00    1.0    1.00  0.00    1    1     0   NaN
Limb*       12 76    2.51  0.53    3.0    2.53  0.00    1    3     2 -0.32
H.F*        13 76    1.99  0.11    2.0    2.00  0.00    1    2     1 -8.38
          kurtosis   se
Age           1.64 0.70
Troop*       -0.39 0.16
Focal*       -1.32 0.39
Species*     -0.99 0.09
Age.1         1.64 0.70
Sex*         -2.02 0.06
Month         0.95 0.04
Day          -0.44 0.80
Year           NaN 0.00
Time*        -1.25 2.53
Category*      NaN 0.00
Limb*        -1.33 0.06
H.F*         69.08 0.01
------------------------------------------------------------ 
Category: LA
          vars n    mean   sd median trimmed  mad  min  max range  skew
Age          1 8   15.12 2.23   16.0   15.12 0.00   10   17     7 -1.42
Troop*       2 8    2.62 0.92    3.0    2.62 0.74    1    4     3 -0.32
Focal*       3 8    2.25 1.58    1.5    2.25 0.74    1    5     4  0.59
Species*     4 8    1.62 0.74    1.5    1.62 0.74    1    3     2  0.54
Age.1        5 8   15.12 2.23   16.0   15.12 0.00   10   17     7 -1.42
Sex*         6 8    1.25 0.46    1.0    1.25 0.00    1    2     1  0.95
Month        7 8    6.62 0.52    7.0    6.62 0.00    6    7     1 -0.42
Day          8 8   14.25 9.33    8.0   14.25 1.48    6   27    21  0.47
Year         9 8 2022.00 0.00 2022.0 2022.00 0.00 2022 2022     0   NaN
Time*       10 8    4.50 2.45    4.5    4.50 2.97    1    8     7  0.00
Category*   11 8    1.00 0.00    1.0    1.00 0.00    1    1     0   NaN
Limb*       12 8    1.62 0.74    1.5    1.62 0.74    1    3     2  0.54
H.F*        13 8    1.50 0.53    1.5    1.50 0.74    1    2     1  0.00
          kurtosis   se
Age           0.56 0.79
Troop*       -1.06 0.32
Focal*       -1.47 0.56
Species*     -1.27 0.26
Age.1         0.56 0.79
Sex*         -1.21 0.16
Month        -2.03 0.18
Day          -1.89 3.30
Year           NaN 0.00
Time*        -1.65 0.87
Category*      NaN 0.00
Limb*        -1.27 0.26
H.F*         -2.23 0.19
------------------------------------------------------------ 
Category: QP
          vars  n    mean   sd median trimmed  mad  min  max range  skew
Age          1 19   16.37 3.30     16   15.76 1.48   14   29    15  2.83
Troop*       2 19    1.68 0.75      2    1.65 1.48    1    3     2  0.52
Focal*       3 19    3.84 1.95      4    3.88 2.97    1    6     5 -0.26
Species*     4 19    1.63 0.50      2    1.65 0.00    1    2     1 -0.50
Age.1        5 19   16.37 3.30     16   15.76 1.48   14   29    15  2.83
Sex*         6 19    1.42 0.51      1    1.41 0.00    1    2     1  0.29
Month        7 19    6.11 0.32      6    6.06 0.00    6    7     1  2.37
Day          8 19   23.89 6.53     27   24.71 2.97    5   29    24 -1.93
Year         9 19 2022.00 0.00   2022 2022.00 0.00 2022 2022     0   NaN
Time*       10 19   10.00 5.63     10   10.00 7.41    1   19    18  0.00
Category*   11 19    1.00 0.00      1    1.00 0.00    1    1     0   NaN
Limb*       12 19    2.47 0.77      3    2.53 0.00    1    3     2 -0.95
H.F*        13 19    1.84 0.37      2    1.88 0.00    1    2     1 -1.73
          kurtosis   se
Age           8.34 0.76
Troop*       -1.16 0.17
Focal*       -1.52 0.45
Species*     -1.84 0.11
Age.1         8.34 0.76
Sex*         -2.01 0.12
Month         3.84 0.07
Day           2.60 1.50
Year           NaN 0.00
Time*        -1.39 1.29
Category*      NaN 0.00
Limb*        -0.74 0.18
H.F*          1.06 0.09
------------------------------------------------------------ 
Category: R
          vars   n    mean    sd median trimmed   mad  min  max range   skew
Age          1 127   11.50  5.25     10   10.72  2.97    5   29    24   2.09
Troop*       2 127    2.70  1.16      3    2.65  0.00    1    5     4  -0.05
Focal*       3 127    5.31  2.48      6    5.31  4.45    1    9     8   0.00
Species*     4 127    2.67  0.69      3    2.83  0.00    1    3     2  -1.76
Age.1        5 127   11.50  5.25     10   10.72  2.97    5   29    24   2.09
Sex*         6 127    1.81  0.39      2    1.88  0.00    1    2     1  -1.57
Month        7 127    6.81  0.39      7    6.88  0.00    6    7     1  -1.57
Day          8 127   12.51  8.69     12   11.87  5.93    1   30    29   0.63
Year         9 127 2022.00  0.00   2022 2022.00  0.00 2022 2022     0    NaN
Time*       10 127   64.00 36.81     64   64.00 47.44    1  127   126   0.00
Category*   11 127    1.00  0.00      1    1.00  0.00    1    1     0    NaN
Limb*       12 127    2.17  0.98      3    2.21  0.00    1    3     2  -0.35
H.F*        13 127    1.99  0.09      2    2.00  0.00    1    2     1 -11.00
          kurtosis   se
Age           5.16 0.47
Troop*       -0.50 0.10
Focal*       -1.40 0.22
Species*      1.41 0.06
Age.1         5.16 0.47
Sex*          0.47 0.03
Month         0.47 0.03
Day          -0.37 0.77
Year           NaN 0.00
Time*        -1.23 3.27
Category*      NaN 0.00
Limb*        -1.89 0.09
H.F*        120.05 0.01
------------------------------------------------------------ 
Category: SG
          vars  n    mean   sd median trimmed  mad  min  max range  skew
Age          1 12   11.67 5.21   15.0    11.9 1.48    5   16    11 -0.41
Troop*       2 12    2.00 0.95    2.0     1.9 1.48    1    4     3  0.58
Focal*       3 12    3.42 1.56    3.5     3.5 2.22    1    5     4 -0.12
Species*     4 12    2.25 0.75    2.0     2.3 1.48    1    3     2 -0.36
Age.1        5 12   11.67 5.21   15.0    11.9 1.48    5   16    11 -0.41
Sex*         6 12    1.58 0.51    2.0     1.6 0.00    1    2     1 -0.30
Month        7 12    6.08 0.29    6.0     6.0 0.00    6    7     1  2.65
Day          8 12   25.25 3.93   27.0    26.0 0.00   14   29    15 -1.85
Year         9 12 2022.00 0.00 2022.0  2022.0 0.00 2022 2022     0   NaN
Time*       10 12    6.50 3.61    6.5     6.5 4.45    1   12    11  0.00
Category*   11 12    1.00 0.00    1.0     1.0 0.00    1    1     0   NaN
Limb*       12 12    1.67 0.78    1.5     1.6 0.74    1    3     2  0.55
H.F*        13 12    1.67 0.49    2.0     1.7 0.00    1    2     1 -0.62
          kurtosis   se
Age          -1.86 1.50
Troop*       -0.78 0.28
Focal*       -1.86 0.45
Species*     -1.33 0.22
Age.1        -1.86 1.50
Sex*         -2.06 0.15
Month         5.48 0.08
Day           2.67 1.14
Year           NaN 0.00
Time*        -1.50 1.04
Category*      NaN 0.00
Limb*        -1.29 0.22
H.F*         -1.74 0.14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># what does the 4 mean??</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Making a DF with just hand grasp data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take out feet use data</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>l_hands <span class="ot">&lt;-</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  L <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(H.F) <span class="sc">%&gt;%</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(H.F, <span class="st">"H"</span>))</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># add the other stuff back</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>l_hands <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(l_hands, L, <span class="at">by =</span> <span class="st">"H.F"</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>l_hands <span class="ot">&lt;-</span> <span class="fu">unique</span>(l_hands)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="co"># actually I also don't want to look at all the categories bc some were added just for fun and are probably not important</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="ot">&lt;-</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  l_hands <span class="sc">%&gt;%</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Category) <span class="sc">%&gt;%</span></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(Category, <span class="st">"E|L|R|SG"</span>))</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a><span class="co"># WHY WON'T IT TAKE OUT LA</span></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a><span class="co"># add the other stuff back why did it even go away</span></span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(l_handstuff, l_hands, <span class="at">by =</span> <span class="st">"Category"</span>)</span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a><span class="co"># I can remove the H.F row because all of it is hand </span></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="ot">&lt;-</span> l_handstuff <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>H.F)</span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a><span class="co"># removing Limb row bc side says the same thing</span></span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-33"><a href="#cb38-33" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="ot">&lt;-</span> l_handstuff <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Limb)</span>
<span id="cb38-34"><a href="#cb38-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-35"><a href="#cb38-35" aria-hidden="true" tabindex="-1"></a><span class="co"># removing mystery duplicates</span></span>
<span id="cb38-36"><a href="#cb38-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-37"><a href="#cb38-37" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="ot">&lt;-</span> <span class="fu">unique</span>(l_handstuff)</span>
<span id="cb38-38"><a href="#cb38-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-39"><a href="#cb38-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-40"><a href="#cb38-40" aria-hidden="true" tabindex="-1"></a>l_noLA <span class="ot">&lt;-</span> </span>
<span id="cb38-41"><a href="#cb38-41" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="sc">%&gt;%</span> </span>
<span id="cb38-42"><a href="#cb38-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">==</span> <span class="st">"E"</span>  <span class="sc">|</span>  Category <span class="sc">==</span> <span class="st">"L"</span> <span class="sc">|</span>  Category <span class="sc">==</span> <span class="st">"R"</span> <span class="sc">|</span>  Category <span class="sc">==</span> <span class="st">"SG"</span> <span class="sc">|</span> Category <span class="sc">!=</span> <span class="st">"LA"</span> )</span>
<span id="cb38-43"><a href="#cb38-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-44"><a href="#cb38-44" aria-hidden="true" tabindex="-1"></a><span class="co">#wow I forgot you can do that</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare hand use by species</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_noLA, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_noLA, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Type of Behavior"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use Between Behaviors"</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Category, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So it looks like lemurs mostly use their right hand for everything except for grooming! Interesting</p>
<p>Now I’m going to filter out the grooming data so it’s all grasping</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>l_grasps <span class="ot">&lt;-</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>l_noLA <span class="sc">%&gt;%</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">==</span> <span class="st">"E"</span>  <span class="sc">|</span>  Category <span class="sc">==</span> <span class="st">"L"</span> <span class="sc">|</span>  Category <span class="sc">==</span> <span class="st">"R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare grasping hand by species</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_grasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Grasping Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What about by sex?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_grasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Grasping Between Sexes"</span>) <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It doesn’t look like there’s really a difference</p>
<p>What about just food grasps?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>l_foodGrasps <span class="ot">&lt;-</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>l_grasps <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">==</span> <span class="st">"E"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Compare grasping hand by species</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Food Grasping Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It really looks like sifakas are more ambidextrous when it comes to food grasping!</p>
<p>What about by individual?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Food Grasping Between Individuals"</span>) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Focal, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It kind of looks like Sophia and Thrax are lefties!!! And Licinius is close… The other lemurs look like righties!</p>
<p>Look at them all on the same scale</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Food Grasping Between Individuals"</span>) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Focal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Okay there isn’t much data for Sophia so it could just be “noise” for her… But Thrax has a lot of data</p>
<p>But is all of this actually statistically significant Don’t know</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_noLA, <span class="fu">aes</span>(<span class="at">x=</span> Category)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Activity"</span>) <span class="sc">+</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Occurrences"</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Activities by Species"</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This just does occurrences. How can I get the Y-axis to be % of L compared to R?</p>
<p>Idk</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Activity"</span>) <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Occurrences"</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Used for Food Grasping Between Species"</span>) <span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Grasping Between Individuals"</span>) <span class="sc">+</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Focal, <span class="at">scales =</span> <span class="st">"free"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Side"</span>) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Occurrences"</span>) <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Used for Food Grasping Between Species"</span>) <span class="sc">+</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> Focal)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Focal"</span>) <span class="sc">+</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Occurrences"</span>) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Side)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_foodGrasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Side"</span>) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Occurrences"</span>) <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Used for Food Grasping Between Sex"</span>) <span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Trying some statistical tests</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>L <span class="sc">%&gt;%</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Side) <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  Side      n proportion
  &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;
1 L       257      0.413
2 R       365      0.587</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>l_handstuff <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Side) <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  Side      n proportion
  &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;
1 L       218      0.417
2 R       305      0.583</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">218</span>, <span class="dv">305</span>, <span class="at">p =</span> .<span class="dv">75</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  218 and 305
number of successes = 218, number of trials = 305, p-value = 0.1648
alternative hypothesis: true probability of success is not equal to 0.75
95 percent confidence interval:
 0.6605189 0.7647621
sample estimates:
probability of success 
             0.7147541 </code></pre>
</div>
</div>
<p>Trying to do chi-squared test and contigency coefficients (did not work)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tbl_handGrasps &lt;- as.data.frame(l_noLA) %&gt;% </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># group_by(Side, Sex) %&gt;% </span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># summarize(qty = sum(Freq)) %&gt;% </span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ungroup() %&gt;% </span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a> <span class="co">#  spread(key = Sex, value = qty)</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co"># mat_handGrasps &lt;- as.matrix(tbl_handGrasps[-1])</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># rownames(mat_handGrasps) &lt;- levels(tbl_handGrasps$Side)</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="co"># chisq.test(mat_handGrasps)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It says it can’t because it doesnt understand “Freq”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_grasps, <span class="fu">aes</span>(<span class="at">x=</span> Side)) <span class="sc">+</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Hand Use for Grasping Between Sexes"</span>) <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Sex, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I echo: false</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (L, <span class="fu">aes</span>(<span class="at">x=</span> Limb)) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Limb"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Individuals"</span>) <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Focal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Not a lot of foot use. It might not be very useful to include these data</p>
<p>Just look at bipedal locomotion</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>l_feet <span class="ot">&lt;-</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>L <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Category <span class="sc">==</span> <span class="st">"BP"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_feet, <span class="fu">aes</span>(<span class="at">x=</span> Limb)) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#C84E00"</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Limb"</span>) <span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Foot Use Between Individuals"</span>) <span class="sc">+</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Focal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I don’t really see any overall patterns here. It looks like Furia leads with her right foor more than left and Thrax leads a little more with his left foot than right.</p>
<p>Does age impact hand use?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(L, <span class="fu">aes</span>(<span class="at">x =</span> Category, <span class="at">y =</span> Age, <span class="at">color =</span> Side)) <span class="sc">+</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>()  <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Type of Behavior"</span>) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Age of Lemur"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Does Age Affect Limb Use?"</span>) <span class="sc">+</span> </span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#1D6363"</span>, <span class="st">"#E89923"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Yeah I don’t think it does lol</p>
<p>Trying to make the graph I yearn for</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_noLA, <span class="fu">aes</span>(<span class="at">x=</span> Category, <span class="at">fill =</span> Side)) <span class="sc">+</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Type of Behavior"</span>) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span> </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#1D6363"</span>, <span class="st">"#E89923"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It’s still not exactly what I want. I want the Y-axis to be % of grasps being with left hand, not total times used. Splitting by color makes it really hard to read, but Idk how else to do it :P</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span> (l_noLA, <span class="fu">aes</span>(<span class="at">x=</span> Side, <span class="at">fill =</span> <span class="fu">interaction</span>(Category, Side))) <span class="sc">+</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Left or Right Side"</span>) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"# of Times Using Each Limb"</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Limb Use Between Lemur Species"</span>) <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span> (<span class="sc">~</span> Species, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="LeftyLemurs_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Wow that it was too complicated. Why did I dare make this monstrosity?</p>
<p>Okay, the landing and foot use data is fun and all, but the hand grasps it what I actually need to look at. I’m going to make that into a .CSV and analyze the data in JMP</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># write_csv (l_grasps, "HandGrasps.csv")</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(l_grasps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Category            Troop              Focal             Species         
 Length:511         Length:511         Length:511         Length:511        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
      Age            Sex                Month            Day       
 Min.   : 5.00   Length:511         Min.   :6.000   Min.   : 1.00  
 1st Qu.:10.00   Class :character   1st Qu.:6.000   1st Qu.: 8.00  
 Median :12.00   Mode  :character   Median :6.000   Median :22.00  
 Mean   :12.05                      Mean   :6.446   Mean   :18.19  
 3rd Qu.:14.00                      3rd Qu.:7.000   3rd Qu.:28.00  
 Max.   :29.00                      Max.   :7.000   Max.   :30.00  
      Year          Time               Side               Note          
 Min.   :2022   Length:511         Length:511         Length:511        
 1st Qu.:2022   Class :character   Class :character   Class :character  
 Median :2022   Mode  :character   Mode  :character   Mode  :character  
 Mean   :2022                                                           
 3rd Qu.:2022                                                           
 Max.   :2022                                                           </code></pre>
</div>
</div>
</section>
<section id="testing-significance" class="level2">
<h2 class="anchored" data-anchor-id="testing-significance">Testing significance:</h2>
<p>Species (significant)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    Emon Lcat Pcoq
  L   66   41  102
  R  128   66  108</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(l_grasps$Side, l_grasps$Species)
X-squared = 9.2063, df = 2, p-value = 0.01002</code></pre>
</div>
</div>
<p>Sex (not significant)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      F   M
  L  57 152
  R  92 210</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Sex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(l_grasps$Side, l_grasps$Sex)
X-squared = 0.46415, df = 1, p-value = 0.4957</code></pre>
</div>
</div>
<p>Focal (significant)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Focal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    Carolina Duggan Furia Gisela Licinius Maddie Randy Rico Rupert Sierra Mist
  L       18      5    13     22       19      6     2   37     27          10
  R       33     18    12     25       29     16     6   61     38          27
   
    Sophia Thrax
  L     10    40
  R      4    33</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Focal))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(table(l_grasps$Side, l_grasps$Focal)): Chi-squared
approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(l_grasps$Side, l_grasps$Focal)
X-squared = 23.257, df = 11, p-value = 0.01626</code></pre>
</div>
</div>
<p>Category (not significant)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Category)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      E   L   R
  L 122  35  52
  R 188  40  74</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Category))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(l_grasps$Side, l_grasps$Category)
X-squared = 1.3451, df = 2, p-value = 0.5104</code></pre>
</div>
</div>
<p>Age (significant)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
     5 10 12 14 16 17 29
  L 50 62 45 15  8 10 19
  R 73 58 71 45 22  4 29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(l_grasps<span class="sc">$</span>Side, l_grasps<span class="sc">$</span>Age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(l_grasps$Side, l_grasps$Age)
X-squared = 20.193, df = 6, p-value = 0.002559</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>